version: '3'
services:
  nginx:
    image: dsapaicoa/orbis-training-docker:2.0.0
    container_name: nginx-deisy
    volumes:
      - ./:/app/    
    working_dir: /app/    
    expose:
      - "3030"
      - "35729"
    ports:
      - 1042:3030
    command: npm start
