version: '3'
services:
  nginx:
    image: dsapaicoa/orbis-training-docker:2.0.0
    container_name: nginx-deisy
    volumes:
      - ./:/app/    
    working_dir: /app/    
    expose:
      - "3030"
      - "35729"
    ports:
      - 1042:3030
    environment:
      - nombre="xD"
    command: >
      bash -c "npm install 
      && npm start && ./resources/example.sh"
  test:
    image: node:10.10.0-slim
    container_name: node-deisy
    depends_on: 
      - nginx
    links:
      - nginx
    restart: on-failure
    command: curl http://nginx:3030